require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/trial_center_branches", type: :request do
  # The controller now requires an authenticated, authorized user. Admin has
  # full permissions; explicit scope avoids the User -> userable delegation bug.
  before { sign_in(FactoryBot.create(:user, :admin), scope: :user) }

  describe "GET /show reps table" do
    it "lists reps in a table with edit/delete actions and a create link" do
      branch = FactoryBot.create(:trial_center_branch)
      FactoryBot.create(:user, userable: FactoryBot.build(:trial_center_branch_rep, trial_center_branch: branch))

      get trial_center_branch_url(branch)

      expect(response).to be_successful
      expect(response.body).to include("Representantes de Sede")
      expect(response.body).to include("Acciones")
      expect(response.body).to include("Editar")
      expect(response.body).to include("Eliminar")
      expect(response.body).to include("Nuevo representante")
    end
  end

  # This should return the minimal set of attributes required to create a valid
  # TrialCenterBranch. As you add validations to TrialCenterBranch, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      TrialCenterBranch.create! valid_attributes
      get trial_center_branches_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      trial_center_branch = TrialCenterBranch.create! valid_attributes
      get trial_center_branch_url(trial_center_branch)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_trial_center_branch_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      trial_center_branch = TrialCenterBranch.create! valid_attributes
      get edit_trial_center_branch_url(trial_center_branch)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new TrialCenterBranch" do
        expect {
          post trial_center_branches_url, params: { trial_center_branch: valid_attributes }
        }.to change(TrialCenterBranch, :count).by(1)
      end

      it "redirects to the created trial_center_branch" do
        post trial_center_branches_url, params: { trial_center_branch: valid_attributes }
        expect(response).to redirect_to(trial_center_branch_url(TrialCenterBranch.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new TrialCenterBranch" do
        expect {
          post trial_center_branches_url, params: { trial_center_branch: invalid_attributes }
        }.to change(TrialCenterBranch, :count).by(0)
      end


      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post trial_center_branches_url, params: { trial_center_branch: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested trial_center_branch" do
        trial_center_branch = TrialCenterBranch.create! valid_attributes
        patch trial_center_branch_url(trial_center_branch), params: { trial_center_branch: new_attributes }
        trial_center_branch.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the trial_center_branch" do
        trial_center_branch = TrialCenterBranch.create! valid_attributes
        patch trial_center_branch_url(trial_center_branch), params: { trial_center_branch: new_attributes }
        trial_center_branch.reload
        expect(response).to redirect_to(trial_center_branch_url(trial_center_branch))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        trial_center_branch = TrialCenterBranch.create! valid_attributes
        patch trial_center_branch_url(trial_center_branch), params: { trial_center_branch: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested trial_center_branch" do
      trial_center_branch = TrialCenterBranch.create! valid_attributes
      expect {
        delete trial_center_branch_url(trial_center_branch)
      }.to change(TrialCenterBranch, :count).by(-1)
    end

    it "redirects to the trial_center_branches list" do
      trial_center_branch = TrialCenterBranch.create! valid_attributes
      delete trial_center_branch_url(trial_center_branch)
      expect(response).to redirect_to(trial_center_branches_url)
    end
  end
end
